<?php

namespace ChirperBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllUsersExceptCurrentLogged($userId) {
        $query = $this
            ->getEntityManager()
            ->createQuery(
                'SELECT u FROM ChirperBundle:User u 
                        WHERE u.id != ?1'
            );

        $query->setParameter(1, $userId);
        return $query->getResult();
    }
}
